# Site settings
title: D3.js 中文實戰教學
email: kevinjipotw@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  kevinchipotw

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge




port: 4000



